version: '3.9'
services: 
    app:
        build:
            context: ./
            dockerfile: ./dockerfile_app/Dockerfile
        command: bash -c "npm run migration:run && npm start"
        restart: always
        volumes: 
            - ./src:/usr/app/src
        ports: 
            - ${PORT}:${PORT}
        networks:
            - my_net_app
        environment: 
            - POSTGRES_HOST=db    
        depends_on: 
            - db
    db:
        build: ./dockerfile_db
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        logging:
            options:
                max-size: 10m
                max-file: "3"
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        volumes:
            - ./postgres-data:${PG_DATA}
        networks:
            - my_net_app
networks: 
    my_net_app:
        driver: bridge
