version: '3.9'
services: 
    app:
        build:
            context: ./
            dockerfile: ./dockerfile_app/Dockerfile
        command: npm start
        restart: always
        ports: 
            - 8080:4000
        networks:
            - my_net_app
    db:
        build: ./dockerfile_db
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        logging:
            options:
                max-size: 10m
                max-file: "3"
        ports:
            - 5438:5432
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
                # copy the sql script to create tables
            - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
               # copy the sql script to fill tables
            - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
        networks:
            - my_net_app
networks: 
    my_net_app:
        driver: bridge
